version: 2
updates:

  # Check for updates to GitHub Actions every month.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    # Group updates to a single PR.
    groups:
      dependencies:
        patterns:
          - '*'
