[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "wheel",
    "setuptools>=64",
    "setuptools_scm[toml]>=8",
]

[tool.setuptools_scm]
local_scheme = "dirty-tag"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rsxX -v --strict-markers --forked"
testpaths = [
    "tests",
]
