[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "wheel",
    "setuptools>=64",
    "setuptools_scm[toml]>=8",
]

[tool.setuptools_scm]
local_scheme = "dirty-tag"
version_file = "src/jaxsim/_version.py"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
minversion = "6.0"
# --forked used to be passed here, but it was removed
# as workaround for compatibility with jax 0.4.25,
# see https://github.com/ami-iit/jaxsim/pull/92#issuecomment-1966290170 
addopts = "-rsxX -v --strict-markers"
testpaths = [
    "tests",
]
