[project]
authors = ["Filippo Luca Ferretti <filippoluca.ferretti@outlook.com>"]
channels = ["conda-forge"]
description = "JAXsim PD controller notebook"
name = "JAXsim examples"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
install = "python -m pip install git+https://github.com/ami-iit/jaxsim.git"
notebook = {cmd = "jupyter notebook PD_controller.ipynb", depends_on = ["install"]}

[dependencies]
ffmpeg = "*"
jax-dataclasses = "*"
jaxlie = "*"
mediapy = "*"
mujoco = "*"
notebook = "*"
pip = "*"
pptree = "*"
rod = "*"
typing-extensions = "*"

[target.osx-64.dependencies]
ml_dtypes = "*"
numpy = "*"
wheel = "*"

[target.osx-64.pypi-dependencies]
jax-metal = "*"

[target.linux-64.dependencies]
jax = "*"
jaxlib = "*"
